---
- name: "Install Packages"
  hosts: all
  gather_facts: false
  user: ubuntu
  # vars_files:
  #   - ./actions.yaml

  tasks:
  - name: Adding install_packages Role
    import_role:
      name: ../roles/install_packages
    tags: "install"