---
- name: "Install Packages"
  hosts: all
  gather_facts: false
  become: yes
  user: ubuntu

  tasks:
    - name: Adding install_packages Role
      include_role:
        name: ../roles/install_packages
      vars:
        install: "yes"
