---
- name: "Install Packages"
  hosts: my_server_group
  gather_facts: false

  tasks:
    - name: Adding install_packages Role
      include_role:
        name: ../roles/install_packages
      vars:
        install: "yes"
